<?php
$a=["a","b","c","d"];
$b=["a","c","x","y"];
?>
<h2>array_diff</h2>
<?php
print_r(array_diff($a,$b));
?>
<h2>array_diff_assoc</h2>
<?php
print_r(array_diff_assoc($a,$b));
?>
<h2>array_intersect</h2>
<?php
print_r(array_intersect($a,$b));
?>
<h2>array_intersect_assoc</h2>
<?php
print_r(array_intersect_assoc($a,$b));
?>